### ISSUE TITLE
Typescript error if parameters in path

### ISSUE THREAD

**Issue by dannylin108** [qdrant/openapi-typescript-fetch#5]
I have the following api definition:

```YAML
/mquery/{q}/{n}:
    get:
      parameters:
      - in: path
        name: q
        schema:
          type: string
        required: true
      - in: path
        name: n
        schema:
          type: number
        required: true
```

Then trying to initialize fetcher:
```Typescript
const mFetcher = fetcher.path('/mquery/{q}/{n}').method('get').create();
```

Typescript complier gives an error:

```
error TS2345: Argument of type '"/mquery/{q}/{n}"' is not assignable to parameter of type 'keyof paths'.
```

Update: sorry, my fault, I used `--path-params-as-types` when generating types, it was the cause.
